name = "felixmarketsapp"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "felixmarketsapp-db"
database_id = "PLACEHOLDER"
migrations_dir = "drizzle/migrations"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "felixmarketsapp-images"

[vars]
ADMIN_PASSWORD = "Fx!M4rk3t$2026sEo"
